//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvidenceMvc_48
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Course_Subject
    {
        [Required]
        public int Id { get; set; }

        [Display(Name ="SubjectName")]
        public string Subject_Name { get; set; }
        public Nullable<int> Course_Id { get; set; }
        public bool Is_Major { get; set; }

      
        public System.DateTime Start_Date { get; set; }
       
        public string Book_Image { get; set; }

        [NotMapped]
        public HttpPostedFileBase Book_Image_Http { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
